### ISSUE TITLE
Add a `retry` decorator

### ISSUE THREAD

**Issue by prkumar** [prkumar/uplink#102]
Here's the original use case from @liiight on [Gitter](https://gitter.im/python-uplink/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge):

> I'm implementing retries in my code, which is done using a package called retry. basically its a super simple decorator, just catch exception, and call the decoratored func until conditions apply, nothing fancy
> when using with uplink, I'm implementing it in the layer above uplink, i.e, the usage of it. i was wondering if it's possible to do it via uplink itself
> i.e, catch an error and retry the called method

**Comment by prkumar** [comment]
This is similar to #71

**Comment by prkumar** [comment]
Here's [my original reply](https://gitter.im/python-uplink/Lobby?at=5b332bb972b31d3691f70a0f). It would be nice if Uplink supported usage of existing decorators for retry, rate-limiting, etc. At the moment, this is not possible (because of how consumer methods are implemented). It might be worth it to consider if and how we should support this usage.

**Comment by bendews** [comment]
An additional use case for this sort of functionality is when auth tokens have a short expiry, on some (admittedly not great) API's I catch an expired token as an exception, refresh it and then try the original request again. Being able to simplify that interaction would be awesome.

**Comment by liiight** [comment]
@bendews You should look into https://github.com/oauthlib/oauthlib and https://requests-oauthlib.readthedocs.io/en/latest/
@prkumar It's kind of a deviation of this issue, but passing custom sessions (like how requests oauthlib implements oauth) would be very cool

**Comment by prkumar** [comment]
@liiight - the `client` constructor argument of a `Consumer` subclass supports `requests.Session` subclasses (like the `OAuth2Session` class from `requests-oauthlib` library). So, although I haven't tried it out, the following should work already:

```python
from requests_oauthlib from OAuth2Session

github_session = OAuth2Session(client_id)
github = GitHub(base_url=BASE_URL, client=github_session)
```

Is this what you're talking about?

**Comment by liiight** [comment]
Exactly, thanks for pointing that out.
@bednews you should check out the links I gave because requests oauthlib can be refresh token internally (when using oauth obviously)

**Comment by bendews** [comment]
@liiight I would have had far less sleepless nights if they were OAuth compliant, trust me on that! 😁

**Comment by prkumar** [comment]
The `retry` decorator should be available in v0.8.0. After I merge #132, I'll create a new alpha release v0.8.0a1 in case you wan't to try it out before the official release. To install this alpha release with pip, do:

```
$ pip install --pre uplink
```

Here's [some documentation](https://uplink.readthedocs.io/en/latest/dev/decorators.html#retry) for the decorator. (I'll also be soon adding a section to the quickstart about this feature). Notably, this decorator can be used like the other decorators, such as `@timeout` or `@headers`:

```python
class GitHub(uplink.Consumer):
    @uplink.retry(max_attempts=2)
    @uplink.get("/users/{user}")
    def get_user(self, user):
        pass
```

If you get the chance to try it out, let me know if you also have any feedback!

CC: @bendews @liiight

**Comment by liiight** [comment]
I haven't had a chance to play with this but the interface look great.

One suggestion though,  you could use native ptrhon status code enum for the retry conditions: https://docs.python.org/3/library/http.html#http.HTTPStatus

**Comment by prkumar** [comment]
@liiight - Thanks for the suggestion! I'll add a way to retry after certain status codes.
