### ISSUE TITLE
Add examples for response & error handling

### ISSUE THREAD

**Issue by prkumar** [prkumar/uplink#113]
We should add examples on how to write response and error handlers using `response_handler` and `error_handler`. Checkout [this guide](https://uplink.readthedocs.io/en/stable/user/quickstart.html#response-and-error-handling) for a quick overview of these decorators.

These examples should reside under the [`examples`](https://github.com/prkumar/uplink/tree/master/examples) directory.

**Comment by schambers** [comment]
I'd like to take a crack at this. I'll likely get to it over the weekend. can you assign it to me?

Thanks!

**Comment by prkumar** [comment]
@schambers - sounds good! Thanks for contributing! Be sure to add your preferred name and username to the `AUTHORS.rst` file 🙂
