### ISSUE TITLE
Small issue in docs

### ISSUE THREAD

**Issue by pdrum** [prkumar/uplink#122]
I think there's a minor issue with this snippet in the docs at https://uplink.readthedocs.io/en/stable/user/quickstart.html#response-and-error-handling
```
def raise_for_status(response):
    """Checks whether or not the response was successful."""
    if 200 <= response.status <= 299:
        raise UnsuccessfulRequest(response.url)

    # Pass through the response.
    return response
```

I think condition of `if` describes a success case rather than a failure. Also if response is `response` of requests library it should probably be `response.status_code`  (Not sure whether `response.status` also works or not. I don't think it does.)

**Comment by prkumar** [comment]
Good catch! This should be fixed.

**Comment by pdrum** [comment]
@prkumar I made a PR for this https://github.com/prkumar/uplink/pull/123
