### ISSUE TITLE
Need a way to avoid sending optional query parameters.

### ISSUE THREAD

**Issue by nphilipp** [prkumar/uplink#125]
**Is your feature request related to a problem? Please describe.**
I've just tried out uplink with an API I want to use (e.g. https://pagure.io/api/0/) which knows no special value for "unset" or "use the default". Currently, uplink always sends all query parameters and…

**Describe the solution you'd like**
I need a way to not send any parameters that aren't set by the user.

**Comment by prkumar** [comment]
@nphilipp - I've merged your fix and will include it in the v0.7 release, which should go live in the next couple hours. 

For what it's worth, a not-so-elegant, imperative workaround is to use a `QueryMap` and handle excluding `None` values manually in a separate method that wraps the invocation of the decorated one:
```python
    @get("/search/commits")
    def _search(self, **query):
        pass

    def search(self, search_term, search_order=None):
        query = {"q": search_term}
        if search_order is not None:
            query["o"] = search_order
        return self._search(**query)
```
However, I prefer your fix over this workaround and agree that omitting `None` should be the default behavior.
