### ISSUE TITLE
Timeout as injectable hook

### ISSUE THREAD

**Issue by daa** [prkumar/uplink#131]
**Is your feature request related to a problem? Please describe.**
I have a need to set timeout on ``Consumer`` object initialization, but as I understand ``uplink.timeout`` decorator allows me to set timeout only on ``Consumer`` subclass definition. To solve this problem I wrapped ``uplink.decorators.timeout.modify_request`` into ``uplink.hooks.RequestAuditor`` and injected that hook in my ``Consumer.__init__`` method as ``self._inject(timeout(t))``. It would be very nice to have an ability to inject timeout like it is possible to inject headers or query parameters.

**Describe the solution you'd like**
I can think of 2 approaches:
- First is to make ``timeout`` to be also a hook and have an ``audit_request()`` method.
- Second is to make an argument ``Timeout``  subclass of ``NamedArgument`` and ``FuncDecoratorMixin`` which will behave similarly to ``Header`` or ``Query`` arguments. Also this will allow to have timeout argument in consumer methods.

**Comment by prkumar** [comment]
@daa - Thanks for the detailed description! I personally favor the second approach, especially because of the additional benefit of using the timeout in consumer methods. We should get this into the next release!

**Comment by daa** [comment]
Thank you, I'll try to make a pull request in some time.
