### ISSUE TITLE
twisted dependency missing?

### ISSUE THREAD

**Issue by mwoodbri** [prkumar/uplink#140]
**Describe the bug**
v0.8.0 appears to be missing a dependency on twisted

**To Reproduce**
```
python3 -mvenv venv
. venv/bin/activate
pip install uplink
python -c 'from uplink import Consumer'

ModuleNotFoundError: No module named 'twisted'
```

**Expected behavior**
No `ModuleNotFoundError`

**Additional context**
The above steps work with v0.7.0

**Comment by prkumar** [comment]
@mwoodbri - Thanks for reporting this! I just opened #141 to remove this mandatory dependency. This post release fix should go live within the hour -- after then, you should be able to import `v0.8.0` without this issue.

**Comment by prkumar** [comment]
Just confirmed that this is fixed now after the recent post release. Thanks again, @mwoodbri!

**Comment by mwoodbri** [comment]
Brilliant. Now working for me. Thank you @prkumar!
