### ISSUE TITLE
Error thrown when following doc example for persisting the token through the consumer’s session property

### ISSUE THREAD

**Issue by ratulotron** [prkumar/uplink#150]
**Describe the bug**
I was following the doc examples for auth to save my access token for a session. However, the code throws an error saying the consumer has no attribute '_Consumer__session':

```
AttributeError at /api/v1/jira/issues/
'Jira' object has no attribute '_Consumer__session'
```

**To Reproduce**
Use the following snippet from the documentation to make a consumer:
```pythhon
class Jira(Consumer):
    def __init__(self, access_token):
        self.session.params["access_token"] = access_token

    @get("/rest/api/3/project/search")
    def get_projects(self):
        """Get paginated list of projects accessible by current user"""
        pass

...

jira_client = JiraConsumer(access_token=access_token, base_url=base_url)
data = jira_client.get_projects()
```

**Expected behavior**
My custom consumer should get authenticated and I should be able to get data from the endpoint.

**Additional context**
I am using Uplink with Django. Also, if I supply the access token while creating a Jira client like this it works perfectly.

```
jira_client = JiraConsumer(base_url=base_url, auth=BearerToken(access_token))
```

**Comment by prkumar** [comment]
@ratulotron - Seems like [the example](https://uplink.readthedocs.io/en/stable/user/quickstart.html#persistence-across-requests-from-a-consumer) in the docs is missing the call to the super class' constructor:

```python
class GitHub(Consumer):

    def __init__(self, base_url, username, password)
        super(Consumer, self).__init__(base_url)

        # Creates the API token for this user
        api_key = create_api_key(username, password)

        # Send the API token as a query parameter with each request.
        self.session.params["api_key"] = api_key

    @get("user/repos")
    def get_user_repos(self, sort_by: Query("sort")):
        """Lists public repositories for the authenticated user."""
```

Adding the `super(Jira, self).__init__` call to the beginning of your constructor should solve this issue. This is a documentation mistake! Thanks for creating an issue for this 👍

**Comment by ratulotron** [comment]
So now my consumer looks like this but still there is a problem.

```Python
class Jira(Consumer):
    """A Python Client for the JIRA API."""
    def __init__(self, user_id, **kwargs):
        access_token = get_token(user_id)
        base_url = os.environ.get("DBNAME", default="connector")
        super(Jira, self).__init__(base_url, **kwargs)
        self.session.params["access_token"] = access_token

    @get("/rest/api/3/project/search")
    def get_projects(self):
        """Get paginated list of projects accessible by current user"""
        pass
```

The problem is, the URL that the consumer is sending request to is broken, as far as I understand, because this is the response I am getting: 

```json
{
    "timestamp": "2019-03-15T19:19:37.772+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/rest/api/3/project/search"
}
```
I made the same request with the full url along with the access token on Postman and it worked fine. Any way to figure out what the final URL the Consumer is making the request to?

**Comment by ratulotron** [comment]
I found out the problem. I did not end the base_url with a slash but started the url in the decorator with a slash. The current version of Uplink seems to support only the scenario where the base url ends with a slash but API endpoints in get/patch decorators start with none. I think this as well should be stated int he documentation.

**Comment by prkumar** [comment]
@ratulotron - No problem! Sorry that I missed your second question. Here's a quick background on how the absolute url is formed.

Uplink uses [`urllib.parse.urljoin`](https://docs.python.org/3/library/urllib.parse.html) to join the `base_url` with the path of the consumer method (i.e., any method decorated with the HTTP method decorators, like `@get` or `@path`). Notably, `urljoin` implements the URL standards ([RFC 1808](https://tools.ietf.org/html/rfc1808.html#section-4), [RFC 3986](https://tools.ietf.org/html/rfc3986#section-5.4) for how to resolve a relative path, using a base url to form an absolute url. As you noted, the documentation is clearly missing this detail, so we should make this clear. 

Regarding how to figure out the final URL the Consumer is making, one way is to use the `MockClient` from our integration test suite (I don't believe we currently deploy this with `uplink`, though, so you'll need to clone the repo beforehand, which is clearly a usability issue -- we should consider distributing the `MockClient` with the library). There isn't any documentation on the `MockClient`, unfortunately; however, there is some details in [the contribution guide](https://github.com/prkumar/uplink/blob/master/CONTRIBUTING.rst#writing-an-integration-test). For example, here is how to use the `MockClient` outside of the integration test suite:

```python
    from uplink import clients
    from tests.integration import MockClient

    client = Mock(spec=clients.interfaces.HttpClientAdapter)
    mock_client = MockClient(client)
    github = GitHub(base_url="https://api.github.com/api/", client=mock_client, username="username", password="password")
    github.get_user_repos(sort_by="created")
    print(mock_client.history[0].url)  # Prints the absolute URL that the consumer used.
```

Importantly, this won't actually send a request, but will give you a way to inspect the details of a sent request.

**Comment by prkumar** [comment]
@ratulotron - I've added a NOTE to the quickstart that should make it clearer how the absolute URL is formed. https://uplink.readthedocs.io/en/latest/user/quickstart.html#defining-an-api-client

Let me know if you have any concerns regarding the wording or the location of the note. Appreciate your input!

**Comment by ratulotron** [comment]
@prkumar hi! Thanks for adding the note, it definitely clears things up! I am absolutely in love with Upllink, however there are some stuff still unclear to me. For example, I saw that there is no way to make the query params optional as of now. The URL I am trying to make request to doesn't need any query param by default, but they are there to filter the data out. On the other hand, since I defined the method like this as per the document, raises error saying the method call is missing required param start_at:

```Python
@returns.json
    @get("rest/api/3/project/search")
    def get_projects(
            self,
            start_at: Query("startAt"),
            max_results: Query("maxResults"),
            order_by: Query("orderBy"),
            query: Query("query"),
            type_key: Query("typeKey"),
            category_id: Query("categoryId"),
            action: Query("action"),
            expand: Query("expand")):
        """Get paginated list of projects accessible by current user"""
        pass
```

I have tried out with adding encode_none=None, but it doesn't seem to work until I called get_projects like this:

```Python
data = jira_client.get_projects(
            start_at=None,
            max_results=None,
            order_by=None,
            query=None,
            type_key=None,
            category_id=None,
            action=None,
            expand=None
        )
```

**Comment by prkumar** [comment]
@ratulotron - That's great to hear! Glad that you've found Uplink helpful, and thank you for providing feedback -- it definitely helps us better serve the community! 😃 

Regarding the question about making params optional: you should be able to get the desired behavior by setting the default of the each argument annotated with `Query` to `None`:
```python
    @returns.json
    @get("rest/api/3/project/search")
    def get_projects(
            self,
            start_at: Query("startAt") = None,
            max_results: Query("maxResults") = None,
            order_by: Query("orderBy") = None,
            query: Query("query") = None,
            type_key: Query("typeKey") = None,
            category_id: Query("categoryId") = None,
            action: Query("action") = None,
            expand: Query("expand") = None):
        """Get paginated list of projects accessible by current user"""
        pass
```
The `None` default value does two things: 1) makes the argument optional per usual, and 2) omits the param from the request if not explicitly set to a non-`None` value. Hence, the following should work now:
```python
data = jira_client.get_projects()
```
Let me know if you run to any trouble with this!

Regarding a forum, we do have a [`gitter`](https://gitter.im/python-uplink/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) lobby for such discussion!

**Comment by ratulotron** [comment]
Thank you so much! Previously when I was setting start_at = None linter was throwing error, later I realized the error was because I set default value for the first param but not others. I feel stupid for not reading the linter warnings carefully :man_facepalming: Thank you so much for your replies. Closing this issue now!
