### ISSUE TITLE
[Feature Request] Support for Deserializing Responses

### ISSUE THREAD

**Issue by prkumar** [prkumar/uplink#16]
# Proposal
A response often details an entity (e.g., a GitHub user or repo) or a collection of entities, rendered in a format such as JSON or XML. Moreover, packages such as [`marshmallow`](https://marshmallow.readthedocs.io/en/latest/) can convert these formats into Python objects, and back. This issue proposes adding a layer to Uplink that handles deserialization simply and declaratively.

The purpose of this ticket is to gauge interest in this feature and track discussion on the possible impact to the public API. Implementation and design ideas are welcome too.

@itstehkman: Tagging you since you brought this up!

**Comment by prkumar** [comment]
Here's possible idea for how the public API might change.

Deserializing a response object might look something like this: to convert the response of a consumer method, use the desired class as the return annotation:

```python
import uplink

# Importing a User schema that we've defined 
# using marshmallow or another library.
from my_schemas import User

class GitHub(uplink.Consumer):
	@uplink.get("/users/{username}")
	def get_user(self, username) -> User:  # I want a user!
      """Get a single user"""
```

A method annotation would be made available for Python 2.7 users:

```python
class GitHub(uplink.Consumer):
    @uplink.returns(User)  # I want a user!
    @uplink.get("/users/{username}")
    def get_user(self, username):
      """Get a single user"""
```


Then, calling `get_user` would return the deserialized object, rather than the response directly.

```python
>> user = github.get_user("prkumar")
>> type(user)
<class 'my_user.User'>
```

@itstehkman: Tagging you since you brought this up!

**Comment by prkumar** [comment]
Notably, the above doesn't cover implementation. To that end, we could possibly borrow from Retrofit, with their [`Converter`](http://square.github.io/retrofit/2.x/retrofit/) and [`Converter.Factory`](http://square.github.io/retrofit/2.x/retrofit/) classes, which provides a good abstraction for different deserialization (and serialization) backends. But, maybe there's more pythonic way?

**Comment by itstehkman** [comment]
Thoughts on using marshmallow: 
I think marshmallow is great at what it does. At first, before reading into the docs enough, I thought it may be annoying for developers to have to create their own schema, and that this would result in some extra glue code for deserializing from the marshmallow schema into a user defined object. There is an ok way of doing this from what I see, and it would still result in glue code, but not too much (hopefully). Here is a good example: http://marshmallow.readthedocs.io/en/latest/quickstart.html#deserializing-to-objects. They still offload creating a new object to some user defined (glue code) constructor, which can still be a bit annoying for the developer. I think it does the job though. 

I was hoping of doing some deserialization similar to what Jackson does with POJOs (plain old java object). I wonder if we can enforce something similar in Python, or if marshmallow can do this for us.

Thoughts on Converter pattern:
This is a general interface, which I think marshmallow basically follows - ie some interface that defines how to serialize/deserialize, so I don't think these suggestions are mutually exclusive at all, actually quite the opposite.

**Comment by prkumar** [comment]
After looking at the `marshmallow` example from   the link you provided, I agree that adding a `Schema` implementation as an intermediate object may be annoying for users not familiar to `marshmallow`. To that end, I opine that we strive for extendability; users should be able to decide the deserializing strategy that works best for them. The converter pattern intends to provide this. For instance, we can provide a converter that deserializes responses using `marshmallow` Schemas, in addition to one that uses a separate framework.

**Comment by prkumar** [comment]
Following my above comment, here's an example of how I'm imagining the converter implementation to look like, using `marshmallow` as an example:

```python
class MarshmallowResponseConverter(interfaces.AbstractConverter):
    """Deserializes response objects using a marshmallow.Schema"""

    def __init__(self, schema):
        self._schema = schema

    def convert(self, response):
        # Deserialize response using schema
        return self._schema.dump(response.content).data


class MarshmallowConverterFactory(interfaces.AbstractConverterFactory):
    @staticmethod
    def get_schema(type_):
        if issubclass(type_, marshmallow.Schema):
            return type_()
        elif isinstance(type_, marshmallow.Schema):
            return type_
        raise ValueError("Expected marshmallow.Scheme subclass or instance.")

    def make_response_body_converter(self, type_, *args, **kwargs):
        try:
            schema = self.get_schema(type_)
        except ValueError:
            return None
        else:
            return MarshmallowResponseConverter(schema)

    def make_request_body_converter(self, type_, *args, **kwargs):
        return None

    def make_string_converter(self, type_, *args, **kwargs):
        return None
```

Then, we provide the converter factory during instantiation of the consumer:
```
github = GitHub(base_url="https://api.github.com", converter_factories=(MarshmallowConverterFactory,))
```

**Comment by itstehkman** [comment]
I think its a good idea! Just curious, why did you choose to use factory pattern? Feels like java, and not very pythonic. This isn't of much concern tbh but I am curious for what is the pythonic way to do this. I did some research to see how pythonic factory pattern is:

https://www.toptal.com/python/python-design-patterns#creational-patterns
https://github.com/faif/python-patterns/blob/140fabe19d30bbbea38343b5f234e9d9255573c6/creational/factory_method.py
https://github.com/faif/python-patterns/blob/345d4e4046231926ba81df0e90aabdfc015691c3/creational/abstract_factory.py

From what I see, i think factory pattern is pythonic, but calling it "*factory" seems so java to me. Curious to know what you think. This is totally secondary to actually getting it to work, and I think what you have suggested is good.
