### ISSUE TITLE
Add doc strings to argument annotation classes

### ISSUE THREAD

**Issue by prkumar** [prkumar/uplink#17]
Argument Annotation classes in `uplink/types.py` are missing class doc strings. To improve code documentation, we need to add doc strings to the following classes, adhering the [Google Style Guide](https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments) for consistency with the rest of the codebase:

- [ ] `uplink.types.Query`
- [ ] `uplink.types.QueryMap`
- [ ] `uplink.types.Header`
- [ ] `uplink.types.HeaderMap`
- [ ] `uplink.types.Field`
- [ ] `uplink.types.FieldMap`
- [ ] `uplink.types.Part`
- [ ] `uplink.types.PartMap`
- [ ] `uplink.types.Body`
- [ ] `uplink.types.Url`

**Comment by FabioRosado** [comment]
Since I've helped with the decorators I might give it a go with this  one as well 😄 
Let me know if you are happy for me to start working on this @prkumar 👍

**Comment by prkumar** [comment]
@FabioRosado, sounds good! 😃
