### ISSUE TITLE
Add doc strings to method annotation classes

### ISSUE THREAD

**Issue by prkumar** [prkumar/uplink#18]
Method annotation classes in `uplink/decorators.py` are missing class doc strings. To improve code documentation, we need to add doc strings to the following classes, adhering the [Google Style Guide](https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments) for consistency with the rest of the codebase:

- [ ] `uplink.decorators.headers`
- [ ] `uplink.decorators.form_url_encode`
- [ ] `uplink.decorators.multipart`
- [ ] `uplink.decorators.json`
- [ ] `uplink.decorators.timeout`
- [ ] `uplink.decorators.args`

**Comment by FabioRosado** [comment]
Hello @prkumar  great project you have here. I could give a hand with this issue if you'd like 👍

**Comment by prkumar** [comment]
Thanks, @FabioRosado! I'll assign this issue to you!

**Comment by prkumar** [comment]
@FabioRosado, feel free to open a PR that references this issue! Thanks for contributing!

**Comment by FabioRosado** [comment]
I've been playing around with uplink while reading the documentation but I'm unsure as to the `    can_be_static = True` that can be found on uplink.decorators. How should I describe this in the docstring?

**Comment by prkumar** [comment]
`can_be_static = True` indicates that the annotation can be a decorator without arguments, like so:
```python
@form_url_encoded  # Notice we don't instantiate `form_url_encoded` directly
@post("/user")
def set_user(self, user): pass
```

This is required because of an implementation detail. Some decorators we provide can be called with arguments (e.g., `headers`) and others without (e.g., `form_url_encoded`). However, they all share some similar decorating logic, which we put in `uplink.decorators.MethodAnnotation.__call__`. Hence, without `call_be_static`, decorators that don't accept arguments, like `form_url_encoded`, would have to be instantiated first so that `form_url_encoded.__call__` is the one wrapping the consumer method:
```
@form_url_encoded()
@post("/user")
def set_user(self, user): pass
```

**Comment by FabioRosado** [comment]
Awesome! Thank you for the great explanation 👍
