### ISSUE TITLE
Relase 0.10.0?

### ISSUE THREAD

**Issue by cognifloyd** [prkumar/uplink#190]
Would it be possible to release 0.10.0? I'd like to use a PyPI release that includes #165.

**Comment by cognifloyd** [comment]
no problem. and thanks again!

**Comment by prkumar** [comment]
@cognifloyd - Released v0.9.1 with #165!

**Comment by prkumar** [comment]
Closing this because #165 should be released now. Let me know if you run into any issues with the new release!

**Comment by cognifloyd** [comment]
Yes. 0.9.1 is working great for me. Thank you!

>
