### ISSUE TITLE
Query with multiple parameters?

### ISSUE THREAD

**Issue by ifiddes** [prkumar/uplink#197]
I was expecting that if I passed a list in to a Query object, like

```
class Test(Consumer):
    @get("/test")
    def get(self, key: Query): pass

t = Test(url)
print(t.get(["a", "b"])
```

That the query would look like `/test?key=a,b`, but instead uplink encodes this as `/test?key=a&key=b`. This then leads to the API dropping the extra keys.

How can I pass in queries that have multiple values? I tried doing `Query(type=list)` but that did not work.

**Comment by liiight** [comment]
@ifiddes use .join() and pass it as a string
