### ISSUE TITLE
urlparse.urljoin restricts URL patterns

### ISSUE THREAD

**Issue by brandonio21** [prkumar/uplink#2]
The [documentation for urljoin](https://docs.python.org/2/library/urlparse.html#urlparse.urljoin) reveals that it has some very strange behavior.  Calling `build(... , base_url="https://example.com")` and also having a method `@get("//unrelated.com/users")` means that the method would execute on "https://unrelated.com/users". 

Is this the intended behavior? I personally think it is very confusing. The following code snippet does not work as one might expect:
```python
request = utils.Request("METHOD", "/api.php?id={id}", {}, None)
uplink_builder.client = http_client_mock
uplink_builder.base_url = "https://example.com/feature"
request_preparer = builder.RequestPreparer(
    uplink_builder, request_definition
)
return_value = request_preparer.prepare_request(request)
assert return_value[0] == "METHOD"
assert return_value[1] == "https://example.com/feature/api.php?id={id}"
assert return_value[2] == {}
```

The above code snippet fails, as `return_value[1]=https://example.com/api.php?id={id}`. 

Should we consider using a simple `path.join()` on URLs? Or should we allow for the complex, yet fairly convoluted behavior? If we want to allow for convoluted behavior (and continue using urljoin), I think it's worth raising an exception if `base_url` is not a true "base" (since its child paths will be trimmed anyway)

**Comment by prkumar** [comment]
I used `urlparse.urljoin` because its behavior corresponds with how Retrofit builds URLs:

<img width="859" alt="screen shot 2017-10-19 at 10 08 09 pm" src="https://user-images.githubusercontent.com/10181244/31806019-1441d15c-b51a-11e7-9c12-07c5d819303c.png">

**Comment by prkumar** [comment]
Following the rule "Endpoint values which contain a leading / are absolute" from above, the code snippet has the expected behavior. 

However, I agree that their behavior is nebulous, and the scenario you presented is a clear example of that.

**Comment by brandonio21** [comment]
Wow.. I never expected to close this issue as "by design". I guess it's just something that I was entirely not used to. But, just to be stubborn, my complaint still stands!

**Comment by prkumar** [comment]
@brandonio21  Definitely a warranted complaint. If we're keeping this behavior, I think adding an explanation of how urls are joined in the documentation is necessary.
