### ISSUE TITLE
Example change from uplink import * to only include used modules

### ISSUE THREAD

**Issue by ivansabik** [prkumar/uplink#20]
Any specific reason why in the example you're importing all packages like this?

```python
from uplink import *
```

References:
- https://stackoverflow.com/questions/2386714/why-is-import-bad

I think in the example we should be doing explicit imports for `headers `, `Consumer `, etc. This is maybe just a following the best practices of python so feel free to close or I could issue a PR fixing those after trying out `uplink`.

**Comment by prkumar** [comment]
I was hoping to avoid a long import statement in the example. But, I agree that we should be promoting best practice. Let's fix this!

Both the `README.rst` and `docs/source/index.rst`, the documentation landing page, will need this change.

**Comment by prkumar** [comment]
@ivansabik: since you offered to open a PR to fix this, I'll assign this issue to you. Thanks for contributing!

**Comment by ivansabik** [comment]
Yes I'll make sometime this week to submit a new PR 👍

**Comment by prkumar** [comment]
Rewrote the README, so this is not needed anymore.
