### ISSUE TITLE
v0.9.4 breaks the returns.json decorator with type=int

### ISSUE THREAD

**Issue by nilsleiffischer** [prkumar/uplink#215]
Before `v0.9.4` this code worked and converted the JSON field to an `int`:

```py
    @uplink.returns.json(key=('metadata', 'length'), type=int)
    @uplink.get('records/{id}')
    def get_record_length(self, record_id: uplink.Path(name='id')):
        pass
```

With `v0.9.4` the endpoint returns a `<Response [200]>` object instead of the expected `int`.

Am I not using the `type` argument of `returns.json` as intended? It would be very useful to be able to do simple type conversions such as this without having to write a model.

**Comment by Imaclean74** [comment]
I see the same thing. Didn’t realize that this used to work.

**Comment by prkumar** [comment]
I know I'm super later here, but in case anyone is running into this issue in v0.9.5 or lower, you should be able to get the pre-v0.9.4 behavior by setting the `cast` argument of `@returns.json` to `True`,

**Comment by prkumar** [comment]
I have PR #215 prepped to restore the v0.9.4 behavior for some built-in types, like `int`

**Comment by prkumar** [comment]
I've merged #229, so this should be fixed in the next minor release. I'm planning to conduct a release for v0.9.6 sometime in the next week.

**Comment by prkumar** [comment]
Here's the tentative CHANGELOG entry:

- Fix @returns.json to cast the JSON response (or field referenced by the key argument) using the type argument when it is a callable type. This effectively reverts a change in the decorator's behavior that was introduced in v0.9.3. (#215)

Let me know if anyone has any thoughts on the entry's clarity. I'm hoping the above message conveys the change's impact succinctly.

**Comment by prkumar** [comment]
This issue should be fixed in v0.9.6

**Comment by leiserfg** [comment]
This is also happening for `Header`

**Comment by prkumar** [comment]
@leiserfg - Can you provide a code sample to help reproduce? Also, could you explain the expected and actual behaviors you are seeing with `Header`?

Thanks!

**Comment by leiserfg** [comment]
I was using it to automatically add the prefix to the token as from certain endpoint I was getting it without it (the "Bearer " part). Maybe I was abusing the API but it worked fine until that change.

**Comment by prkumar** [comment]
@leiserfg - Got it. If I understand correctly, you were using `Header` for something like this: 

```
def addBearerToken(token):
    return "Bearer " + token

@uplink.get('user')
def get_user(self, bearer_token: Header(type=addBearerPrefix)):
    pass
```
