### ISSUE TITLE
Subclasses of Consumers Not Behaving as Expected

### ISSUE THREAD

**Issue by brandonio21** [prkumar/uplink#23]
Consider the following scenario:

```python
class StoreAPI(Consumer):
    @get("/api/item?id={id}")
    def get_item(self, id):
         pass

class ProtectedStoreAPI(StoreAPI):
    def __init__(self, user_id):
        super().__init__()
        self.user_id = user_id

    def get_item(self, id):
         if allowed(self.user_id):
             return super().get_item(id)
```

In the above scenario, I attempt to implement a "wrapper" around a consumer. The wrapper, being a subclass, can still be passed around just as the consumer was, but the wrapper has some extra security features.

The problem arises, however, when calling `super().get_item()` in the wrapper. Since everything is built dynamically, the method "ProtectedStoreAPI::get_movie" is not detected as a `RequestDefinitionBuilder` and is not turned into a callable. Neither is the `StoreAPI::get_movie` since its overriden. Thus, nothing is ever built into a `CallBuilder` and the `StoreAPI` cannot be called.

Note, however, that everything is fine when the protected API calls the method something other than `get_item`, since then `StoreAPI::get_movie` is exposed and can be built.

I've been working with this for the better part of a few hours and can't come up with a good solution. I've tried adding a new `@overrides` decorator and a new Mixin class.. both seemed promising, but no dice.

I think this is a pretty valid usecase and it's a shame it doesn't work. I'll do investigations in my free time and keep this issue updated. Please chime in if you know anything!

**Comment by prkumar** [comment]
@brandonio21:

I think we can use a [descriptor](https://docs.python.org/3/howto/descriptor.html) to solve this. We could make each consumer method (e.g., `ProtectedStoreAPI::get_item`) a non-data descriptor that constructs the `CallBuilder` when the attribute is accessed on an instance. I have a few thoughts on how this might work, the refactoring it would entail, and the impact it would have on how things are built -- I'll organize my thoughts and post them here later tonight.

**Comment by prkumar** [comment]
@brandonio21, Here's a proposal, following my above comment. 

## Explanation

The implementation entails changing `RequestDefinitionBuilder` into a non-data descriptor then moving the building of the `CallFactory` from the instantiation of the consumer instance (i.e., `Consumer::__init__`) to the access of the consumer method (i.e., `RequestDefinitionBuilder.__get__`). This change should fix the problem since we're relying on python's built-in attribute access protocol, instead of trying to hijack it on instantiation.

## Proposal

First, let's remove `Consumer::_build`, and save the builder instance created in `Consumer::__init__` to the instance variable `self.__builder`:

```python
class Consumer(object):
    def __init__(
            self,
            base_url="",
            client=None,
            hook=None,
            converter_factories=()
    ):
        self._builder = builder = Builder()
        builder.base_url = base_url
        builder.add_converter_factory(*converter_factories)
        if client is not None:
            builder.client = client
        if hook is not None:
            builder.hook = hook
```

Next, define the `__get__` method to make `uplink.interfaces.RequestDefinitionBuilder` a non-data descriptor:

```python
class RequestDefinitionBuilder(object):

    def __get__(self, instance, owner):
        if instance is not None:
            # Moved from `uplink.builders.Builder.build`:
            try:
                definition = self.build()
            except exceptions.InvalidRequestDefinition as error:
                # TODO: Find a Python 2.7 compatible way to reraise
                raise exceptions.UplinkBuilderError(
                    owner.__name__,
                    self.__name__,
                    error
                )

            # Create callable using consumer's builder: 
            return instance._builder.build(instance, definition)
        else:
            return self
```

And that should do it!

## Impact

The impact here is that each access of the consumer method (e.g., StoreAPI().get_movie()) creates a new `RequestDefinition` and `CallFactory`. Currently, we create a `RequestDefinition` and `CallFactory` for each instantiation. However, we could mitigate this with some lazy-loading.

**Comment by brandonio21** [comment]
This LGTM, but I think that the double-build adds way too much overhead. The built object can definitely be memoized, as such:

```python
try:
    from functools import lru_cache as memoize
except ImportError:
    def memoize(func):
        memo = {}
        def wrapper(*args):
            return memo.setdefault(args, func(*args))
       return wrapper


class RequestDefinitionBuilder(object):

    @memoize
    def __get__(self, instance, owner):
        if instance is not None:
            # Moved from `uplink.builders.Builder.build`:
            try:
                definition = self.build()
            except exceptions.InvalidRequestDefinition as error:
                # TODO: Find a Python 2.7 compatible way to reraise
                raise exceptions.UplinkBuilderError(
                    owner.__name__,
                    self.__name__,
                    error
                )

            # Create callable using consumer's builder: 
            return instance._builder.build(instance, definition)
        else:
            return self
```

**Comment by prkumar** [comment]
Yup, sounds good! Memoizing looks equivalent but cleaner than lazy-loading in this case. 👍

**Comment by brandonio21** [comment]
I'll go ahead and implement. Stand by for PR
