### ISSUE TITLE
Minimum required version of "six" package doesn't work

### ISSUE THREAD

**Issue by godotgildor** [prkumar/uplink#246]
https://github.com/prkumar/uplink/blob/cca6f787dfb5c40a5093182560699ad7d56da159/setup.py#L18

Upon importing uplink, when I have uplink 0.9.5 installed with version 1.12.0 of the "six" package, I am seeing an error like:
`AttributeError: module 'six.moves' has no attribute 'collections_abc'`

Upgrading "six" to version 1.13.0 works though.

**Comment by prkumar** [comment]
What version of Python are you using?

**Comment by godotgildor** [comment]
I noticed this when installing to a python 3.7.12 environment

**Comment by prkumar** [comment]
Should be fixed with v0.9.6
