### ISSUE TITLE
Optional twisted/aiohttp dependencies

### ISSUE THREAD

**Issue by kadrach** [prkumar/uplink#32]
Hi @prkumar,

after seeing [this comment](https://github.com/prkumar/uplink/blob/ff6945d8672fb295f1ab61731282260409116238/setup.py#L19), just wanted to check if you're open to a PR for this.

How about optional `[twisted]` and `[aiohttp]` extras with `requests` always being installed?
```python
install_requires = [
    "requests>=2.18.0",
    "uritemplate>=3.0.0"
]
extras_require = {
    "twisted": ["twisted>=17.1.0"],
    "aiohttp:python_version>='3.4.2'": ["aiohttp>=2.3.0"]
}
```

Ideally, Python would give us the option of "install at least one of these 3", but I couldn't figure out if setuptools supports a "default" extra.

Alternatively see approach below, the serious downside being that uplink does not "work out of the box" if one were to `pip install uplink`.
```python
extras_require = {
    "requests": ["requests>=2.18.0"],
    "twisted": ["twisted>=17.1.0"],
    "aiohttp:python_version>='3.4.2'": ["aiohttp>=2.3.0"]
}

**Comment by prkumar** [comment]
I’m certainly open to a PR for this! My preference is your initial approach, where `requests` is mandatory and `twisted` and `aiohttp` are extras.

**Comment by prkumar** [comment]
@kadrach, would you have some time to tackle this? Of course, no worries if not! Asking so that I can assign it appropriately. Thanks again for the suggestion!
