### ISSUE TITLE
How can pass parameters to request method?

### ISSUE THREAD

**Issue by ni3galave** [prkumar/uplink#55]
I want to call HTTPS Rest API using uplink.Consumer. API provides authorization by specifying Authorization token in the headers as shown below:

```
BASE_URL = "https://localhost:3780/"

@uplink.headers({
    "Content-Type": "application/json",
    "Authorization":"Basic YWRtaW46Z3VydWppMTI="
})
```
So when I call any REST API it gives me SSL certifaction error as follows:

`requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=3780): Max retries exceeded with url: /api/3/assets/1 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))`

Uplinks internally calls [request method](http://docs.python-requests.org/en/master/api/#module-requests) and request method has SSL to true by default  ( i.e verify=True )
I want set verify property to false. How can I do that?

**Comment by prkumar** [comment]
You could provide a custom `requests.Session` instance using the `client` parameter:
```python
session = requests.Session()
session.verify = False
myapi = MyAPI(BASE_URL, client=session)
```

**Comment by ni3galave** [comment]
It says: 
```
  File "/usr/local/lib/python3.5/dist-packages/uplink/builder.py", line 43, in __init__
    self._client = self._client()
TypeError: 'Session' object is not callable
```

Here is my sample code:

### Asset.py
```
class Asset(uplink.Consumer):
    @uplink.json
    @uplink.get("/api/3/assets/{id}")
    def get_asset_info(self, id):
        "Get asset info"

```
### Asset_example.py

```
if __name__ == "__main__":
    session = requests.Session()
    session.verify = False
    asset = Asset(BASE_URL, client=session)
    ass = asset.get_asset_info(1).json()
    print("==================================================");
    print(ass);
```
Let me know if I am wrong.

**Comment by prkumar** [comment]
Thanks for the info! Looking at the error's traceback, it seems that you're running Uplink v0.2. Could you verify by checking the module's `__version__` attribute:

```python
>>> import uplink
>>> uplink.__version__
'0.3.0'
```

**Comment by prkumar** [comment]
If you are using v0.2, then you'll need to wrap the `session` instance inside an [`uplink.RequestsClient`](https://uplink.readthedocs.io/en/latest/clients.html#uplink.RequestsClient):

```python
if __name__ == "__main__":
    session = requests.Session()
    session.verify = False
    asset = Asset(BASE_URL, client=uplink.RequestsClient(session))
    ass = asset.get_asset_info(1).json()
    print("==================================================");
    print(ass);
```

**Comment by ni3galave** [comment]
I am actually using 0.2.2 uplink version and mentioned both the solution works for me. :+1: 

Thanks for the quick response and solution :)

**Comment by prkumar** [comment]
@ni3galave Nice!
