### ISSUE TITLE
Drop nomenclature of using decorators for argument annotation

### ISSUE THREAD

**Issue by ppslim** [prkumar/uplink#56]
As taken from https://uplink.readthedocs.io/en/latest/tips.html#annotating-your-arguments-for-python-2-7

> For one, annotations can work as function decorators. With this approach, annotations are mapped to arguments from “bottom-up”.

The nomenclature used here is an extremely frustrating way of working with argument annotations outside of Python 3.

For myself, I am in the world of still trying to wrap my head around making my code portable, so for the time being, the obvious approach to using uplink is to make use of decorators in place of annotations.

However, on viewing the document around this, by far and a mile, the use of `args` as a substitute to an annotation, should be the primary explanation.

The current primary explanation in short, almost made my eyes bleed, whilst trying to wrap my head around it. To somebody that reads right to left and (or only) left to right, I could see this being a somewhat simpler concept, but I know for absolute certain I wouldn't want to encounter this approach again.

Technically, I understand why the "Bottom up" rule applied. With each executed decorator which processes top down, it is essentially creating a new call to be executed in the stack, whilst appending the existing and ordered stack to the end of itself.

With the arguments itself, they are read left to right as expected, with the left most (excluding `self`) popping the oldest (bottom most) item from the  `args` stack, and continuing to pop the oldest for each arg.

But something is my mind at least, doesn't want to compute this (least of all 8am on a Monday as it did yesterday).

The `@uplink.args` methodology is the better description and much simpler to handle. Left to right, matching the actual arguments excluding `self`.

In all seriousness, the fact that they are implemented such that you could annotate each with a its own decorator is pretty novel, but the complicated comprehension when used practically, I would seriously suggest is removed from the docs, if not at minimum re-ordered.

From a coding standards perspective and even just basic ability to read code, the separate decorators and thus ordering, would not pass for personally. Though I could not answer this for others.

**Comment by prkumar** [comment]
Thanks for the honest, detailed feedback! I think you're completely right. Nowadays, I'm using Python 3 more regularly than Python 2.7, which I think is why I hadn't entirely appreciated the difficulty of this paradigm until now, from reading your crucible. From personal experience, when writing code with uplink that needed to be compatible for Python 2.7, I would normally gravitate towards using the `@arg` decorator, especially for methods with more than two or three arguments. Given my own reluctance, it's an embarrassing oversight on my part that I didn't consider then how bewildering this approach would be for new users.

Anyways, as you suggested, I think we should either:

1. reorder that subsection and have the `@uplink.args` approach be the primary explanation
2. remove the decorator approach entirely

If we go with (1), what do you think about this redesign of the decorator approach: we could rework to behave like how [Click](http://click.pocoo.org/6/) does it, using the "Top down" rule. So, the top-most decorator annotates the left-most argument (ignoring, `self`):

```python
@uplink.Url
@uplink.Path
@uplink.get
def get_commit(self, commits_url, sha): pass
```

**Comment by prkumar** [comment]
Removed the confusing nomenclature from the docs in v0.4. Will create a new issue to consider reordering the decorator approach, as suggested in my above comment.
