### ISSUE TITLE
Method headers cannot override previously defined Class headers

### ISSUE THREAD

**Issue by ppslim** [prkumar/uplink#72]
In an attempt to write a custom module to provide specific external system interaction, I observed that I cannot override my header at method level. I will move to a new decorator eventually, but custom headers are a good start, as I will use them extensively anyway and header behaviour is tested, so I thought it can prove code outside of my struggle to write a new decorator,

The example below uses a class level and method level header. Same key, new value, with what I thought would trigger an override, but doesn't.

The response is always `uplink.abc.ExecClassOp`, unless I remove the class level one. Commenting out the class level header (for the same header key) correctly returns `uplink.abc.ExecMethodOp`.

```python
uri = 'https://jsonplaceholder.typicode.com/'

@timeout(10)
@headers({'X-UplinkAuthIntercept': 'uplink.abc.ExecClassOp'})
class JSONp(Consumer):
  @get('users')
  def get_users(self): pass
  
  @timeout(15)
  @headers({'X-UplinkAuthIntercept': 'uplink.abc.ExecMethodOp'})
  @get('users/{id}')
  def get_user(self, user_id: Path('id')): pass

class SessionWrapper(object):
  def __init__(self):
    self._session = requests.Session()
    
  def request(self, *args, **kwargs):
    print('Session.request: args={0}, kwargs: {1}'.format(args, kwargs))
    return self._session.request(*args, **kwargs)

api = JSONp(base_url=uri, client=RequestsClient(SessionWrapper()))
user = api.get_user(2)
print('Header: {0}'.format(user.request.headers))
```

Session wrapper here is to provide working insight only.

**Comment by prkumar** [comment]
Thanks for detailed explanation, @ppslim! This problem definitely looks like a bug. The intended behavior is for the method headers to override the class headers, as you expected. The same goes for the timeout.

The root cause here is pretty straight-forward: uplink is executing the class level decorators after the method level ones. Fortunately, the fix should be pretty straight-forward. I'll get the PR up soon.

**Comment by prkumar** [comment]
@ppslim - The fix is live in v0.4.1 release, which you can download now with `pip`.

**Comment by prkumar** [comment]
Reopening this so @ppslim can confir

**Comment by ppslim** [comment]
FYI, I have confirmed. Many thanks.
