### ISSUE TITLE
How to use non-json request and response bodies with uplink, for example protobuf?

### ISSUE THREAD

**Issue by daa** [prkumar/uplink#89]
I could annotate request parameter with ``uplink.Body(RqModel)``, response with ``uplink.returns(RsModel)`` where ``RqModel`` and ``RsModel`` are corresponding request and response protobuf classes and make my own converter to and from them at 0.4.1 but in version 0.5.0 ``Body`` requires dict to be returned from converter and ``returns`` disappeared. I solved the issue by restoring old behaviour with my own decorators but I have a question: how one is supposed to use models and their custom serialization and deserialization scheme with uplink since 0.5.0?

**Comment by prkumar** [comment]
Thanks for bringing this to attention, @daa. For one, `Body` should still accept types other than `dict`, so the new behavior in 0.5.0 is a regression. I have patched it locally and will include in a patch release that should go out today. 

Regarding the disappearance of `returns`, I have a quick question regarding your use case in 0.4.1: are you writing a custom `ConverterFactory` that encapsulates the protobuf serialization and deserialization?

**Comment by daa** [comment]
Thank you for the fix. Yes, I've made my own ``ConverterFactory`` to deal with protobuf, I looked at ``models.loads`` and ``dumps`` decorators but could not use them because of ``Body`` issue and the fact that I have to write python2.7-compatible code and thus ``returns`` was required for me.

Also I should note it was a pleasure to write client using ``uplink``, thank you.

**Comment by daa** [comment]
Now I tested my code with updated uplink and everything works fine, thanks.
