### ISSUE TITLE
Consider interface for asynchronous requests

### ISSUE THREAD

**Issue by prkumar** [prkumar/uplink#9]
The purpose of this ticket is to track discussion on this feature's impact to the Public API.

**Comment by itstehkman** [comment]
What would be a good way to implement this you think? If we are using python 3.x, asyncio looks quite promising. Here is some example/comparison with gevents and tornado: https://hackernoon.com/asynchronous-python-45df84b82434

There is also quora's asynq library. I don't think we should build our own async library for uplink. If we want to support python 2, we might not be able to use asyncio.
